/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaceGrafica;
import FornecedorApple.Apple;
import Lojas.*;
import dadosDoEstoqueDaApple.DadosDosProdutosApple;
import interfaces.*;
/**
 *
 * @author guilherme
 */
public class JanelaEstoqueDaApple extends javax.swing.JFrame {
    Apple fornecedor = new Apple();
    Loja1 loja1 = new Loja1(fornecedor);
    Loja2 loja2 = new Loja2(fornecedor);
    Loja3 loja3 = new Loja3(fornecedor);
    /**
     * Creates new form JanelaEstoqueDaApple
     */
    public JanelaEstoqueDaApple() {
        initComponents();
    }
    
    private void verificarSeENumero(java.awt.event.KeyEvent evt){
        if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldQuantidadeDeIphone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldQuantidadeDeIpad = new javax.swing.JTextField();
        jTextFieldQuantidadeDeIpadAir = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldQuantidadeDeIpadPro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldQuantidadeDeIpadMini = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldQuantidadeDeMacBookAir = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldQuantidadeDeMacBookPro = new javax.swing.JTextField();
        jButtonAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldQuantidadeDeIphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQuantidadeDeIphoneKeyTyped(evt);
            }
        });

        jLabel1.setText("Iphone");

        jLabel2.setText("Ipad");

        jTextFieldQuantidadeDeIpad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQuantidadeDeIpadKeyTyped(evt);
            }
        });

        jTextFieldQuantidadeDeIpadAir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQuantidadeDeIpadAirKeyTyped(evt);
            }
        });

        jLabel3.setText("Ipad Air");

        jTextFieldQuantidadeDeIpadPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQuantidadeDeIpadProKeyTyped(evt);
            }
        });

        jLabel4.setText("Ipad Pro");

        jLabel5.setText("Ipad Mini");

        jTextFieldQuantidadeDeIpadMini.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQuantidadeDeIpadMiniKeyTyped(evt);
            }
        });

        jLabel6.setText("Mac Book Air");

        jTextFieldQuantidadeDeMacBookAir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQuantidadeDeMacBookAirKeyTyped(evt);
            }
        });

        jLabel7.setText("Mac Book Pro");

        jTextFieldQuantidadeDeMacBookPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQuantidadeDeMacBookProKeyTyped(evt);
            }
        });

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldQuantidadeDeMacBookPro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQuantidadeDeMacBookAir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldQuantidadeDeIpad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQuantidadeDeIphone, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldQuantidadeDeIpadAir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQuantidadeDeIpadPro, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQuantidadeDeIpadMini, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButtonAtualizar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuantidadeDeIphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldQuantidadeDeIpad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuantidadeDeIpadAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuantidadeDeIpadPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldQuantidadeDeIpadMini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldQuantidadeDeMacBookAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldQuantidadeDeMacBookPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButtonAtualizar)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        int quantidadeDeIphone = Integer.parseInt(jTextFieldQuantidadeDeIphone.getText());
        
        int quantidadeDeIpad = Integer.parseInt(jTextFieldQuantidadeDeIpad.getText());
        int quantidadeDeIpadAir = Integer.parseInt(jTextFieldQuantidadeDeIpadAir.getText());
        int quantidadeDeIpadPro = Integer.parseInt(jTextFieldQuantidadeDeIpadPro.getText());
        int quantidadeDeIpadMini = Integer.parseInt(jTextFieldQuantidadeDeIpadMini.getText());
        
        int quantidadeDeMacBookAir = Integer.parseInt(jTextFieldQuantidadeDeMacBookAir.getText());
        int quantidadeDeMacBookPro = Integer.parseInt(jTextFieldQuantidadeDeMacBookPro.getText());
        
        DadosDosProdutosApple dados = new DadosDosProdutosApple(quantidadeDeIphone, quantidadeDeIpad,
        quantidadeDeIpadAir, quantidadeDeIpadPro, quantidadeDeIpadMini, quantidadeDeMacBookAir, quantidadeDeMacBookPro);
        
        fornecedor.setDados(dados);
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jTextFieldQuantidadeDeIphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeDeIphoneKeyTyped
        verificarSeENumero(evt);
    }//GEN-LAST:event_jTextFieldQuantidadeDeIphoneKeyTyped

    private void jTextFieldQuantidadeDeIpadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeDeIpadKeyTyped
        verificarSeENumero(evt);
    }//GEN-LAST:event_jTextFieldQuantidadeDeIpadKeyTyped

    private void jTextFieldQuantidadeDeIpadAirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeDeIpadAirKeyTyped
        verificarSeENumero(evt);
    }//GEN-LAST:event_jTextFieldQuantidadeDeIpadAirKeyTyped

    private void jTextFieldQuantidadeDeIpadProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeDeIpadProKeyTyped
        verificarSeENumero(evt);
    }//GEN-LAST:event_jTextFieldQuantidadeDeIpadProKeyTyped

    private void jTextFieldQuantidadeDeIpadMiniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeDeIpadMiniKeyTyped
        verificarSeENumero(evt);
    }//GEN-LAST:event_jTextFieldQuantidadeDeIpadMiniKeyTyped

    private void jTextFieldQuantidadeDeMacBookAirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeDeMacBookAirKeyTyped
        verificarSeENumero(evt);
    }//GEN-LAST:event_jTextFieldQuantidadeDeMacBookAirKeyTyped

    private void jTextFieldQuantidadeDeMacBookProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeDeMacBookProKeyTyped
        verificarSeENumero(evt);
    }//GEN-LAST:event_jTextFieldQuantidadeDeMacBookProKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaEstoqueDaApple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaEstoqueDaApple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaEstoqueDaApple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaEstoqueDaApple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaEstoqueDaApple().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldQuantidadeDeIpad;
    private javax.swing.JTextField jTextFieldQuantidadeDeIpadAir;
    private javax.swing.JTextField jTextFieldQuantidadeDeIpadMini;
    private javax.swing.JTextField jTextFieldQuantidadeDeIpadPro;
    private javax.swing.JTextField jTextFieldQuantidadeDeIphone;
    private javax.swing.JTextField jTextFieldQuantidadeDeMacBookAir;
    private javax.swing.JTextField jTextFieldQuantidadeDeMacBookPro;
    // End of variables declaration//GEN-END:variables
}
