/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacegrafica;
import javax.swing.JOptionPane;
import modelos.basicos.*;
import modelos.decorador.*;
/**
 *
 * @author guilherme
 */
public class TelaDePedido extends javax.swing.JFrame {
    private IHamburger hamburger = new HamburgerComCarne();
    private String quantidade_str = "";
    
    public void atualizarHamburger(){
        if(jComboBoxOpcoesDeHamburger.getSelectedIndex() == 0){
            hamburger = new HamburgerComCarne();
            jTextAreaDescricao.setText("Descrição: Pão, carne, queijo\n");
            jLabelPreco.setText("Preço: R$ 30.00");
        }
        else if(jComboBoxOpcoesDeHamburger.getSelectedIndex() == 1){
            hamburger = new HamburgerComFrango();
            jTextAreaDescricao.setText("Descrição: Pão, frango, queijo\n");
            jLabelPreco.setText("Preço: R$ 40.00");
        }
        
        quantidade_str = "";
        if(jComboBoxQuantidadesDeAlfaces.isEnabled()){
            int quantidade = jComboBoxQuantidadesDeAlfaces.getSelectedIndex()+1;
            for(int i=0;i<quantidade;i++)
                hamburger = new Alface(hamburger);
            
            quantidade_str += String.valueOf(quantidade) + " x Alfaces\n";
        }
        
        if(jComboBoxQuantidadesDeTomates.isEnabled()){
            int quantidade = jComboBoxQuantidadesDeTomates.getSelectedIndex()+1;
            for(int i=0;i<quantidade;i++)
                hamburger = new Tomate(hamburger);
            
            quantidade_str += String.valueOf(quantidade) + " x Tomates\n";
        }
        
        if(jComboBoxQuantidadesDeCebolas.isEnabled()){
            int quantidade = jComboBoxQuantidadesDeCebolas.getSelectedIndex()+1;
            for(int i=0;i<quantidade;i++)
                hamburger = new Cebola(hamburger);
            
            quantidade_str += String.valueOf(quantidade) + " x Cebolas\n";
        }
        
        if(jComboBoxQuantidadesDeQueijos.isEnabled()){
            int quantidade = jComboBoxQuantidadesDeQueijos.getSelectedIndex()+1;
            for(int i=0;i<quantidade;i++)
                hamburger = new Queijo(hamburger);
            
            quantidade_str += String.valueOf(quantidade) + " x Queijos\n";
        }
        
        if(jComboBoxQuantidadesDeBacons.isEnabled()){
            int quantidade = jComboBoxQuantidadesDeBacons.getSelectedIndex()+1;
            for(int i=0;i<quantidade;i++)
                hamburger = new Bacon(hamburger);
            
            quantidade_str += String.valueOf(quantidade) + " x Bacons\n";
        }
        
        if(jComboBoxQuantidadesDeOvosFritos.isEnabled()){
            int quantidade = jComboBoxQuantidadesDeOvosFritos.getSelectedIndex()+1;
            for(int i=0;i<quantidade;i++)
                hamburger = new OvoFrito(hamburger);
            
            quantidade_str += String.valueOf(quantidade) + " x Ovos fritos\n";
        }
        
        jTextAreaDescricao.setText(jTextAreaDescricao.getText() + quantidade_str);
        jLabelPreco.setText("Preço: R$" + Double.toString(hamburger.preco()));
    }
    /**
     * Creates new form TelaDePedido
     */
    public TelaDePedido() {
        initComponents();
        jComboBoxQuantidadesDeAlfaces.setEnabled(false);
        jComboBoxQuantidadesDeTomates.setEnabled(false);
        jComboBoxQuantidadesDeCebolas.setEnabled(false);
        jComboBoxQuantidadesDeQueijos.setEnabled(false);
        jComboBoxQuantidadesDeBacons.setEnabled(false);
        jComboBoxQuantidadesDeOvosFritos.setEnabled(false);
        
        jTextAreaDescricao.setWrapStyleWord(true);
        jTextAreaDescricao.setLineWrap(true);
        jTextAreaDescricao.setOpaque(false);
        jTextAreaDescricao.setEditable(false);
        jTextAreaDescricao.setFocusable(false);
        
        atualizarHamburger();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHamburgeria = new javax.swing.JLabel();
        jComboBoxOpcoesDeHamburger = new javax.swing.JComboBox<>();
        jLabelEscolherHamburger = new javax.swing.JLabel();
        jLabelPreco = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxAlface = new javax.swing.JCheckBox();
        jCheckBoxTomate = new javax.swing.JCheckBox();
        jCheckBoxCebola = new javax.swing.JCheckBox();
        jCheckBoxOvoFrito = new javax.swing.JCheckBox();
        jCheckBoxQueijo = new javax.swing.JCheckBox();
        jCheckBoxBacon = new javax.swing.JCheckBox();
        jComboBoxQuantidadesDeAlfaces = new javax.swing.JComboBox<>();
        jComboBoxQuantidadesDeTomates = new javax.swing.JComboBox<>();
        jComboBoxQuantidadesDeCebolas = new javax.swing.JComboBox<>();
        jComboBoxQuantidadesDeQueijos = new javax.swing.JComboBox<>();
        jComboBoxQuantidadesDeBacons = new javax.swing.JComboBox<>();
        jComboBoxQuantidadesDeOvosFritos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jButtonPedir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelHamburgeria.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabelHamburgeria.setText("Hamburgeria");

        jComboBoxOpcoesDeHamburger.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jComboBoxOpcoesDeHamburger.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hamburger com carne", "Hamburger com frango" }));
        jComboBoxOpcoesDeHamburger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOpcoesDeHamburgerActionPerformed(evt);
            }
        });

        jLabelEscolherHamburger.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabelEscolherHamburger.setText("Hamburger:");

        jLabelPreco.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabelPreco.setText("Preço: R$ 30,00");

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel1.setText("Adicionais:");

        jCheckBoxAlface.setText("Alface");
        jCheckBoxAlface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAlfaceActionPerformed(evt);
            }
        });

        jCheckBoxTomate.setText("Tomate");
        jCheckBoxTomate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTomateActionPerformed(evt);
            }
        });

        jCheckBoxCebola.setText("Cebola");
        jCheckBoxCebola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCebolaActionPerformed(evt);
            }
        });

        jCheckBoxOvoFrito.setText("Ovo Frito");
        jCheckBoxOvoFrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOvoFritoActionPerformed(evt);
            }
        });

        jCheckBoxQueijo.setText("Queijo");
        jCheckBoxQueijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxQueijoActionPerformed(evt);
            }
        });

        jCheckBoxBacon.setText("Bacon");
        jCheckBoxBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBaconActionPerformed(evt);
            }
        });

        jComboBoxQuantidadesDeAlfaces.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10" }));
        jComboBoxQuantidadesDeAlfaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxQuantidadesDeAlfacesActionPerformed(evt);
            }
        });

        jComboBoxQuantidadesDeTomates.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10"}));
        jComboBoxQuantidadesDeTomates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxQuantidadesDeTomatesActionPerformed(evt);
            }
        });

        jComboBoxQuantidadesDeCebolas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10" }));
        jComboBoxQuantidadesDeCebolas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxQuantidadesDeCebolasActionPerformed(evt);
            }
        });

        jComboBoxQuantidadesDeQueijos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10" }));
        jComboBoxQuantidadesDeQueijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxQuantidadesDeQueijosActionPerformed(evt);
            }
        });

        jComboBoxQuantidadesDeBacons.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10" }));
        jComboBoxQuantidadesDeBacons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxQuantidadesDeBaconsActionPerformed(evt);
            }
        });

        jComboBoxQuantidadesDeOvosFritos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10" }));
        jComboBoxQuantidadesDeOvosFritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxQuantidadesDeOvosFritosActionPerformed(evt);
            }
        });

        jTextAreaDescricao.setEditable(false);
        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        jButtonPedir.setText("Pedir");
        jButtonPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEscolherHamburger)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxOpcoesDeHamburger, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelPreco)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxCebola)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxQuantidadesDeCebolas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jCheckBoxAlface)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxQuantidadesDeAlfaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jCheckBoxTomate)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jComboBoxQuantidadesDeTomates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxBacon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxQuantidadesDeBacons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxOvoFrito)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxQuantidadesDeOvosFritos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonPedir)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jCheckBoxQueijo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jComboBoxQuantidadesDeQueijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabelHamburgeria)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHamburgeria)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEscolherHamburger)
                    .addComponent(jComboBoxOpcoesDeHamburger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPreco)
                    .addComponent(jButtonPedir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAlface)
                    .addComponent(jComboBoxQuantidadesDeAlfaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxQueijo)
                    .addComponent(jComboBoxQuantidadesDeQueijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTomate)
                    .addComponent(jCheckBoxBacon)
                    .addComponent(jComboBoxQuantidadesDeTomates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxQuantidadesDeBacons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxCebola)
                    .addComponent(jCheckBoxOvoFrito)
                    .addComponent(jComboBoxQuantidadesDeCebolas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxQuantidadesDeOvosFritos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxOpcoesDeHamburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOpcoesDeHamburgerActionPerformed
        atualizarHamburger();
    }//GEN-LAST:event_jComboBoxOpcoesDeHamburgerActionPerformed

    private void jCheckBoxAlfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAlfaceActionPerformed
        if(jComboBoxQuantidadesDeAlfaces.isEnabled())
            jComboBoxQuantidadesDeAlfaces.setEnabled(false);
        else
            jComboBoxQuantidadesDeAlfaces.setEnabled(true);
        
        atualizarHamburger();
    }//GEN-LAST:event_jCheckBoxAlfaceActionPerformed

    private void jComboBoxQuantidadesDeAlfacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxQuantidadesDeAlfacesActionPerformed
        atualizarHamburger();
    }//GEN-LAST:event_jComboBoxQuantidadesDeAlfacesActionPerformed

    private void jCheckBoxTomateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTomateActionPerformed
        if(jComboBoxQuantidadesDeTomates.isEnabled())
            jComboBoxQuantidadesDeTomates.setEnabled(false);
        else
            jComboBoxQuantidadesDeTomates.setEnabled(true);
        
        atualizarHamburger();
    }//GEN-LAST:event_jCheckBoxTomateActionPerformed

    private void jComboBoxQuantidadesDeTomatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxQuantidadesDeTomatesActionPerformed
        atualizarHamburger();
    }//GEN-LAST:event_jComboBoxQuantidadesDeTomatesActionPerformed

    private void jCheckBoxCebolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCebolaActionPerformed
        if(jComboBoxQuantidadesDeCebolas.isEnabled())
            jComboBoxQuantidadesDeCebolas.setEnabled(false);
        else
            jComboBoxQuantidadesDeCebolas.setEnabled(true);
        
        atualizarHamburger();
    }//GEN-LAST:event_jCheckBoxCebolaActionPerformed

    private void jComboBoxQuantidadesDeCebolasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxQuantidadesDeCebolasActionPerformed
        atualizarHamburger();
    }//GEN-LAST:event_jComboBoxQuantidadesDeCebolasActionPerformed

    private void jCheckBoxQueijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxQueijoActionPerformed
        if(jComboBoxQuantidadesDeQueijos.isEnabled())
            jComboBoxQuantidadesDeQueijos.setEnabled(false);
        else
            jComboBoxQuantidadesDeQueijos.setEnabled(true);
        
        atualizarHamburger();
    }//GEN-LAST:event_jCheckBoxQueijoActionPerformed

    private void jComboBoxQuantidadesDeQueijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxQuantidadesDeQueijosActionPerformed
        atualizarHamburger();
    }//GEN-LAST:event_jComboBoxQuantidadesDeQueijosActionPerformed

    private void jCheckBoxBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBaconActionPerformed
        if(jComboBoxQuantidadesDeBacons.isEnabled())
            jComboBoxQuantidadesDeBacons.setEnabled(false);
        else
            jComboBoxQuantidadesDeBacons.setEnabled(true);
        
        atualizarHamburger();
    }//GEN-LAST:event_jCheckBoxBaconActionPerformed

    private void jComboBoxQuantidadesDeBaconsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxQuantidadesDeBaconsActionPerformed
        atualizarHamburger();
    }//GEN-LAST:event_jComboBoxQuantidadesDeBaconsActionPerformed

    private void jCheckBoxOvoFritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOvoFritoActionPerformed
        if(jComboBoxQuantidadesDeOvosFritos.isEnabled())
            jComboBoxQuantidadesDeOvosFritos.setEnabled(false);
        else
            jComboBoxQuantidadesDeOvosFritos.setEnabled(true);
        
        atualizarHamburger();
    }//GEN-LAST:event_jCheckBoxOvoFritoActionPerformed

    private void jComboBoxQuantidadesDeOvosFritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxQuantidadesDeOvosFritosActionPerformed
        atualizarHamburger();
    }//GEN-LAST:event_jComboBoxQuantidadesDeOvosFritosActionPerformed

    private void jButtonPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedirActionPerformed
        JOptionPane.showMessageDialog(null,"Pedido feito com sucesso! ;)\n\n" + jTextAreaDescricao.getText() + "\nPreço: R$ " + Double.toString(hamburger.preco()));
    }//GEN-LAST:event_jButtonPedirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDePedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPedir;
    private javax.swing.JCheckBox jCheckBoxAlface;
    private javax.swing.JCheckBox jCheckBoxBacon;
    private javax.swing.JCheckBox jCheckBoxCebola;
    private javax.swing.JCheckBox jCheckBoxOvoFrito;
    private javax.swing.JCheckBox jCheckBoxQueijo;
    private javax.swing.JCheckBox jCheckBoxTomate;
    private javax.swing.JComboBox<String> jComboBoxOpcoesDeHamburger;
    private javax.swing.JComboBox<String> jComboBoxQuantidadesDeAlfaces;
    private javax.swing.JComboBox<String> jComboBoxQuantidadesDeBacons;
    private javax.swing.JComboBox<String> jComboBoxQuantidadesDeCebolas;
    private javax.swing.JComboBox<String> jComboBoxQuantidadesDeOvosFritos;
    private javax.swing.JComboBox<String> jComboBoxQuantidadesDeQueijos;
    private javax.swing.JComboBox<String> jComboBoxQuantidadesDeTomates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEscolherHamburger;
    private javax.swing.JLabel jLabelHamburgeria;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescricao;
    // End of variables declaration//GEN-END:variables
}
